### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by Mohabsher** [web-ecom-37/Gads_Ecommerce_App_api#2]
C:\Users\Mahmed\Documents\GitHub\Gads_Ecommerce_App_api>npm start

> ecommerce@1.0.0 start C:\Users\Mahmed\Documents\GitHub\Gads_Ecommerce_App_api
> node app.js

C:\Users\Mahmed\Documents\GitHub\Gads_Ecommerce_App_api\node_modules\express-jwt\lib\index.js:20
  if (!options || !options.secret) throw new Error('secret should be set');
                                   ^

Error: secret should be set
    at module.exports (C:\Users\Mahmed\Documents\GitHub\Gads_Ecommerce_App_api\node_modules\express-jwt\lib\index.js:20:42)
    at Object.<anonymous> (C:\Users\Mahmed\Documents\GitHub\Gads_Ecommerce_App_api\api\lib\controllers\auth.js:54:25)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Mahmed\Documents\GitHub\Gads_Ecommerce_App_api\api\lib\veiws\auth\auth.js:9:5)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ecommerce@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ecommerce@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mahmed\AppData\Roaming\npm-cache\_logs\2020-10-21T18_04_50_779Z-debug.log
[2020-10-21T18_04_50_779Z-debug.log](https://github.com/kabahima/Gads_Ecommerce_App_api/files/5417936/2020-10-21T18_04_50_779Z-debug.log)

**Comment by kabahima** [comment]
#2
Please create a .env file within your project repo
add the following in this file 
DATABASE = "<use a mongodb connect >"
JWT_SECRET = "<"PUT IN YOUR KEY">"

> it will work
